hadoop-servers:
  hosts:
    192.168.122.253:
      ansible_user: root
      disk_path: /dev/vdb
      vg_name: vg_hadoop_data
      pvs_name: /dev/vdb1
      lv_name: lv_hadoop_data
      mount_point: "{{ HADOOP_DATA }}"
      file_system: ext4