- name: Download Min.io
  get_url:
    url: https://dl.min.io/server/minio/release/linux-amd64/minio
    dest: /opt/minio/bin/minio
    mode: '0755'
    owner: "{{ app_user }}"
    group: "{{ app_user }}"

- name: Copy Min.io configuration file
  template:
    src: minio.conf.j2
    dest: "{{ minio_workdir }}/minio.conf"
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: "0600"
    force: yes

- name: Copy Min.io Systemd file
  template:
    src: minio.service.j2
    dest: /etc/systemd/system/minio.service
    mode: "0755"
    force: yes

- name: Start Min.io server
  systemd:
    name: minio.service
    state: started
    enabled: yes
    daemon_reload: yes


