minio-servers:
  hosts:
    192.168.0.101:
      ansible_user: root
      disk_path: /dev/sdb
      pvs_name: /dev/sdb
      vg_name: MinioVolGroup
      lv_name: MinioLogVolume
      file_system: xfs
      minio_workdir: /opt/minio
      mount_point: "{{ minio_workdir }}/data"
      app_user: minio
      minio_root_user: minio_admin
      minio_root_pass: minio_admin
      SSL_CERT: true
      minio_domain: files.example.local
      minio_server_url: "http://{{ minio_domain }}"